model:
  name: 'resnet50_fc512'
  pretrained: True

data:
  type: 'image'
  source: 'whaleshark'
  height: 256
  width: 256
  transforms_train: ['center_crop', 'random_affine', 'color_jitter', 'random_grayscale', 'blur']
  transforms_test: ['center_crop', 'resize']
  version: 'v2'

loss:
  name: 'triplet'
  triplet:
    weight_t: 1.
    weight_x: 1.
  softmax:
    label_smooth: True

sampler:
  num_instances: 4
  num_copies: 4

train:
  optim: 'adam'
  lr: 0.00001
  max_epoch: 200
  batch_size: 64
  fixbase_epoch: 1
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'multi_step'
  stepsize: [110]

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
